---
- name: Install Pod Network
  hosts: g2
  become: true
  tasks:
    - name: Install Flannel network add-on
      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml